	# Setar a imagem base
FROM redis

	# Autor/Mantenedor
MAINTAINER Mateus Gomes

	# Atualizar o repositório e instalar o server do Redis
# RUN yum update && yum install -y redis-server

	# Expor Redis na porta 6379
EXPOSE 6379

	# Rodar Redis Server
# ENTRYPOINT  ["/usr/bin/redis-server"]